### ISSUE TITLE
Consolidating URL / service address configuration

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#103]
We currently store URL /service configuration in portal-ui index.html.
Similar to the move of auth.json configuration from portal-ui to portal-fe, same method can be applied for URL configuration so only PROXY is left in index.html.

**Comment by kohsah** [comment]
To Do:
only  
`GAWATI_PROXY` should remain in index.html
The other two parameters should be moved into `gawati.json` in portal-fe. 
Same applies to `profiles-ui`.

**Comment by kohsah** [comment]
GAWATI_DOCUMENT_SERVER , GAWATI_PROFILES_SERVER settings in portal-ui `index.html` have been moved into portal-fe/configs/gawati.json: 
```json
{
	"internal" : {
		"gawati-portal-ui":{
			"urlBase": "http://localhost:3000"
		},
		"gawati-portal-fe":{
			"urlBase": "http://localhost:9001"
		},
		"gawati-profiles-ui":{
			"urlBase": "http://localhost:9004"
		},
		"gawati-profiles-fe":{
			"urlBase": "http://localhost:9003"
		}
	},
	"client": {
		"gawati-profiles-ui" : {
			"urlBase" : "http://localhost:9004"
		},
		"gawati-media-server": {
			"urlBase": "http://media.local"
		},
		"gawati-data-server" : {
			"urlBase": "http://data.local"
		}

	}
}
```

Specifically the `client` settings:
```
	"client": {
		"gawati-profiles-ui" : {
			"urlBase" : "http://localhost:9004"
		},
		"gawati-media-server": {
			"urlBase": "http://media.local"
		},
		"gawati-data-server" : {
			"urlBase": "http://data.local"
		}
```
