### ISSUE TITLE
Fix links in document view page to use the filter route

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#11]
The links int he document page (and also in the listings page ) for each document use the older style route links ..they need to be updated to use the filter style links : 

![image](https://user-images.githubusercontent.com/5685392/34718629-7139bdc4-f55d-11e7-84c1-e805f4bc2cb0.png)

**Comment by Arunadevi** [comment]
For the category link ("Legislation"), do we use the `keywords `filter?

**Comment by kohsah** [comment]
For now just leave it as a dummy link there is no filtering by type implemented at the moment ...
