### ISSUE TITLE
Autorearrange for small screen across languages

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#12]
For english, if the width of screen is reduced such that Logo and searchbox dont fit in one line, these are arranged vertically in a nice centered way. For the alternative languages portuguese and french, the behaviour differs in that it forms a kind of 2 line block style. Probably sth missing in the translation related resources.

**Comment by ccsmart** [comment]
Actually i now understand its a feature, maybe not a good one though. It just happens to be that in english edition, the two lines next to the logo have the same width. The autoreformat happens for each line separate. Mybe the two lines should be defined/joined into one block, so that theres just 1 autoreformat case/step.

**Comment by kohsah** [comment]
Just adding a screenshot of the problem:

**Comment by ccsmart** [comment]
I actually meant this, when continuously shrinking width...
OK:
![image](https://user-images.githubusercontent.com/9324800/34761871-de821fd8-f5e5-11e7-80fa-d7d6bde5213c.png)

NOK:
![image](https://user-images.githubusercontent.com/9324800/34761900-0192ad4e-f5e6-11e7-929b-94e38653164d.png)

OK:
![image](https://user-images.githubusercontent.com/9324800/34761922-1730127c-f5e6-11e7-94e4-518cbee8e85a.png)

**Comment by ccsmart** [comment]
The last push introduced a fourth arrangement state:
State 4
![image](https://user-images.githubusercontent.com/9324800/35211201-c2db7fbc-ff55-11e7-8415-3b2d1d1aa65f.png)
This state should be removed, as well as state 2 in previous examples.
Only states 1 and state 3 should exist.

**Comment by kohsah** [comment]
The notification button placement gets messed up in smaller dimensions - this seems to be a result of moving the notification container out of the body 

![image](https://user-images.githubusercontent.com/5685392/35259616-ddc6b382-002c-11e8-918e-1e8c93499471.png)

**Comment by kohsah** [comment]
This issue was fixed, will close pending verification

**Comment by ccsmart** [comment]
It has improved. It seems now the two text lines are correctly treated as one. But somewhere there is still a step/corner being interpreted in the arrangement. It's most visible in french, but you have to be careful to hit the spot:
![image](https://user-images.githubusercontent.com/9324800/35322344-358a8216-00ea-11e8-8c74-f9a5983144bc.png)

**Comment by ccsmart** [comment]
Just realised, when you do hit that spot, there is an effect trickling down into the document collection:
![image](https://user-images.githubusercontent.com/9324800/35322458-b32061dc-00ea-11e8-96b8-db3d2f8bcbb4.png)

**Comment by Arunadevi** [comment]
@ccsmart , can you please give some hints how I can get to view the misalignment specified above?  I tried different browser sizes in the French page.  However, I'm not able to get the arrangement above. Hints like browser, version,  machine resolution, screen size will be very helpful if possible.

**Comment by ccsmart** [comment]
I would like to show you directly on my PC.
Trying to contact you on slack.

**Comment by kohsah** [comment]
@ccsmart Actually IE 11 is the wrong base for testing.  If you look at browser usage stats, IE 11 use is rapidly falling.  It isn't even among the top 3 browsers. 

https://www.w3counter.com/globalstats.php
https://caniuse.com/usage-table

That said, we should still make it work on IE 11, but i think in terms of priorities it isnt the highest one.

**Comment by kohsah** [comment]
Closing this.
