### ISSUE TITLE
i18n - convert all literal strings to i18n prefixed strings

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#14]
Currently many texts are literal : 

``` javascript
            <li><strong>Document Number:</strong> {anFRBRnumber(doc, type).showAs}</li>

```
This needs to be translation prefixed : 

``` javascript
            <li><strong>T("Document Number:")</strong> {anFRBRnumber(doc, type).showAs}</li>

```

and the String needs to be added to translations.json (in english)

**Comment by kohsah** [comment]
1. Dates need to be localized as per locale 
2. Country names in filter dropdown need to be localized

**Comment by Arunadevi** [comment]
What about countries and languages above the thumbnail?
![image](https://user-images.githubusercontent.com/3785744/36887785-bc8122a2-1e18-11e8-9999-0e1558d0ae9a.png)

**Comment by kohsah** [comment]
@Arunadevi Same applies to those. They need to be localized too.

**Comment by Arunadevi** [comment]
Updated issue-#34 branch.  Please let me know if I should rename the branch.
