### ISSUE TITLE
npm install warning

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#15]
Got this in build:
node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Seems to hardcode Debian.

**Comment by kohsah** [comment]
This is a downstream bug (if it can be called that)  not ours .. 

https://github.com/yarnpkg/yarn/issues/2564
