### ISSUE TITLE
In mobile view the mobile menu does not open 

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#17]
The filter on the right becomes the mobile menu (highlighted in yellow) -- it does not open anymore

![image](https://user-images.githubusercontent.com/5685392/35143134-9502e26e-fd26-11e7-9489-f5c0064249c9.png)

**Comment by kohsah** [comment]
This may be useful: https://github.com/kunukn/react-slide-toggle

**Comment by Arunadevi** [comment]
Will have to change to a different slider component.

**Comment by kohsah** [comment]
@Arunadevi  We could write our own implementation -- see https://stackoverflow.com/questions/29949331/convert-jquery-slidetoggle-code-to-javascript for vanilla JS  implementation of slideToggle, this can be ported to React

**Comment by kohsah** [comment]
There are some layout issues in mobile view -- different dimensions... 

![image](https://user-images.githubusercontent.com/5685392/35849794-cff04b3e-0b48-11e8-8883-5ff1025b05e3.png)


![image](https://user-images.githubusercontent.com/5685392/35849856-0b91a00c-0b49-11e8-8554-b112dff61337.png)

There needs to be some minimum width height set, otherwise it shrinks all the way down: 

![image](https://user-images.githubusercontent.com/5685392/35849938-3ae99a9e-0b49-11e8-8252-3636fb88eb60.png)

**Comment by kohsah** [comment]
Tested with updated commit: 

![image](https://user-images.githubusercontent.com/5685392/35862713-9e01842e-0b72-11e8-87f4-f9d38504fa95.png)

**Comment by kohsah** [comment]
Fixed.
