### ISSUE TITLE
Migrate from Bootstrap 4 alpha 6 to Bootstrap 4 final 

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#18]
Currently the portal is based on Bootstrap 4  Alpha 6. 

It needs to be upgraded to Bootstrap 4 final. 

Note that we don't use the JS aspects of Bootstrap - we use the React port ReactStrap to provide the JS aspects.

Only the css needs to be migrated.

**Comment by Arunadevi** [comment]
Verified on Chrome, Firefox, Edge, IE.  (Windows)

**Comment by kohsah** [comment]
The page has become a fixed width page since the upgrade:

![image](https://user-images.githubusercontent.com/5685392/35637535-7d65e49a-06da-11e8-91a3-7f747bef26b5.png)

There were some overrides in app-custom for bootstrap 4 alpha 6 which i think have not been carried over.

**Comment by Arunadevi** [comment]
The `.container`s are responsive fixed-width containers.  `.container-fluid` is what we need here.  (http://boosted.orange.com/v4-alpha/layout/overview/#containers).  However, I don't understand why the following were not changed in alpha:

**Comment by kohsah** [comment]
@Arunadevi 

Just adding this in bootstrap-overrides.css seemed to fix it for me locally :

```
diff --git a/src/css/bootstrap-overrides.css b/src/css/bootstrap-overrides.css
index 94cc1cd..6244600 100644
--- a/src/css/bootstrap-overrides.css
+++ b/src/css/bootstrap-overrides.css
@@ -49,7 +49,8 @@ h1, .h1 {

 @media (min-width: 1200px) {
     .container {
-      width: 97%;
+      width: 97% !important;
+      max-width: 100%;
     }
 }


```

**Comment by Arunadevi** [comment]
Yes, it would. But per Bootstrap docs, container-fluid is meant for the purpose.  I feel changing .container's definition to work like .container-fluid may not be the right way to do it.

**Comment by kohsah** [comment]
@Arunadevi Ok lets give container-fluid a try, if that works fine.
