### ISSUE TITLE
Themes paginator does not work

### ISSUE THREAD

**Issue by Arunadevi** [gawati/gawati-portal-ui#19]
`GET /gw/service/themes/expressions/summary/?lang=eng&themes=trade%7Cgoods%7Csupplies&count=10&from=11&to=20&text=2 HTTP/1.1`
is the Request URL upon clicking the 2nd page link which receives 
`{ "timestamp" : "2018-01-29T13:16:19.167+05:30", "exprAbstracts" : { "orderedby" : "dt-updated-desc", "records" : "0", "pagesize" : "", "itemsfrom" : "", "totalpages" : "", "currentpage" : "0", "empty" : { "message" : { "lang" : "eng", "#text" : "\n                        No documents dound\n                        " } } } }`

The request that fetches desired result:
`GET /gw/service/themes/expressions/summary/?themes=trade&themes=goods&themes=supplies&count=10&from=1&to=10 HTTP/1.1`

**Comment by kohsah** [comment]
Closing this for now
