### ISSUE TITLE
Path routing issue with back button

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#2]
Hitting the back button results in a page reload in some cases.

**Comment by kohsah** [comment]
@Arunadevi This seems to be related react router config

**Comment by Arunadevi** [comment]
I'm not seeing the issue of current page reloading on back button unless the previous page has the same hash as the current.  But what I do see while paginating and hitting back button is that the URL changes but page does NOT change.

**Comment by kohsah** [comment]
@Arunadevi Ah.. Indeed i see that now. so we use the HashRouter at the moment (index.js): 

```
ReactDOM.render(
    <HashRouter>
        <App />
    </HashRouter>, 
    document.getElementById('root')
);
registerServiceWorker();

```

Perhaps we need to switch to the BrowserRouter of react router

**Comment by kohsah** [comment]
@Arunadevi i saw the problem ....its with the routing maps one path to one component. But we can map the same route to multiple components so each of those will be rendered independently.

**Comment by Arunadevi** [comment]
Looks like, anyway, BrowserRouter is a must for our dynamic application.

**Comment by Arunadevi** [comment]
The browser back during pagination works if I define the `componentWillReceiveProps` function:
```
componentWillReceiveProps(nextProps) {
        this.getListing({
            count: parseInt(nextProps.match.params.count),
            from: parseInt(nextProps.match.params.from),
            to: parseInt(nextProps.match.params.to)
        });
    }
```

**Comment by kohsah** [comment]
Cool, that resolved it
