### ISSUE TITLE
Search bar gets smaller than necessary

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#20]
![image](https://user-images.githubusercontent.com/9324800/35514698-5a436804-0507-11e8-9e4b-08e00a74a104.png)

**Comment by kohsah** [comment]
Instead of "GO" in the search button use an icon ...since GO has different lengths in different languages:

https://fontawesome.com/icons/search?style=solid

**Comment by Arunadevi** [comment]
Changed to icon.  On issue-#20 branch.

**Comment by kohsah** [comment]
@Arunadevi That branch is a bit out of date, the merge has many conflicts, can you put the changes in a fresh branch cut from master.

**Comment by Arunadevi** [comment]
Done.  On search-bar branch.
