### ISSUE TITLE
Languages as installable language packs

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#23]
Currently language strings are part of gawati-portal-ui. This is not an ideal scenario, there are other UI components in Gawati which are independent of gawati-portal-ui and if they have to use language strings they will need to duplicate it. 

We need language strings to be installable packages - where the language string is managed within that Package (i.e. poeditor manages the language strings of that package) and the package is installable within gawati-portal-ui (or any other package) 

i.e. Languages need to be installable as packages. So language strings would move to their own projects, and be installed as packages into the package where they are required. 

e.g.`npm install gawati-language-packs`

> Possibility of language packs /language downloads?
> Considering independent additions of languages through POE editor, should there be a method to individually choose language sets for installations / add remove languages by an administrator ?

**Comment by kohsah** [comment]
We have moved language strings to a separate package: https://github.com/gawati/gawati-lang-packs

**Comment by kohsah** [comment]
Issue has been fixed with 8f6db0f162c5527877efc38316721e07e603fe37
