### ISSUE TITLE
Missing Links in the UI

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#27]
See, nigeria is not linked in the breadcrumb

![image](https://user-images.githubusercontent.com/5685392/35850522-23ad23bc-0b4b-11e8-9553-ae63e121a7ec.png)

**Comment by kohsah** [comment]
@Arunadevi  See the tags below, they are broken : 

![image](https://user-images.githubusercontent.com/5685392/36949019-e36f97da-2008-11e8-9649-85be0294d9fc.png)

**Comment by Arunadevi** [comment]
Updated tag-links branch

**Comment by kohsah** [comment]
Closing this, since all seems OK. Reopen if someone sees a problem
