### ISSUE TITLE
Filter Bug: Multiple simultaneous requests

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#28]
When we add multiple filters quickly, the new filter request is made concurrently with an earlier one leading to 2 stacked pages. 

this is more evident on large volume sites where there is a slight delay in processing the request.  The promise of the earlier filter request needs to be cancelled before making the new request.

**Comment by Arunadevi** [comment]
- Added a debounce for the filter call
- Not updating component state when it is unmounted
- Using cancel token and canceling previous request. ( May be we should remove this if the above fixes suffice)

Updated `stale-response` branch

**Comment by kohsah** [comment]
Closing this
