### ISSUE TITLE
URL results in a 404 on refresh

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#33]
visit https://dev.gawati.org

it redirects to https://dev.gawati.org/_lang/en/

if you hit the browser refresh button now on the redirected page, we get a 404 error. 

The problem manifested since the change from HashRouter to BrowserRouter

**Comment by Arunadevi** [comment]
https://dev.gawati.org/static/css/main.db7f4033.css  in the first case is
changed to  https://dev.gawati.org/_lang/en/static/css/main.db7f4033.css in
the second

**Comment by kohsah** [comment]
@Arunadevi ok the browserrouter has possibly broken the homepage="." config in package.json ... "#" has a different meaning in the context of urls so setting "." to homepage in that case was not breaking the url boundaries ...

**Comment by kohsah** [comment]
This is related to changes in issue #26

**Comment by kohsah** [comment]
See this comment: https://github.com/gawati/gawati-portal-ui/issues/26#issuecomment-369182793  that basically contains the fix for the 404 ... basically instead of "." for the  homepage setting use a specific domain / vdir path

**Comment by kohsah** [comment]
Here is the correct httpd conf to resolve this issue (Note the use of `RewriteCond` below which resolves the refresh 404 issue. This isn't there currently. Will update the documentation to reflect the same. 

```
<VirtualHost *:80>
ProxyRequests off
ServerName gawati.local
ServerAlias gawati.local

DocumentRoot "path/to/gawati-portal-ui/build"

<Directory  "path/to/gawati-portal-ui/build">
	DirectoryIndex "index.html"
	Require all granted
	AllowOverride All
    
    ## the following is required for client side routing to work, 
    ## otherwise results in a 404 on refresh
    
    RewriteEngine on
    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
    # Rewrite everything else to index.html to allow html5 state links
    RewriteRule ^ index.html [L]
</Directory>

Alias /akn "path/to/pdf/akn"
<Directory "path/to/pdf/akn">	
	DirectoryIndex "index.html"
	Require all granted
	AllowOverride All
</Directory>

<Location ~ "/gwd/(.*)">
  AddType text/cache-manifest .appcache
  ProxyPassMatch  "http://localhost:8080/exist/restxq/gw/$1"
  ProxyPassReverse "http://localhost:8080/exist/restxq/gw/$1"
  ProxyPassReverseCookiePath /exist /
  SetEnv force-proxy-request-1.0 1
  SetEnv proxy-nokeepalive 1
</Location>

<Location ~ "/gwp/(.*)">
  AddType text/cache-manifest .appcache
  ProxyPassMatch  "http://localhost:9001/gwp/$1"
  ProxyPassReverse "http://localhost:9001/gwp/$1"
  SetEnv force-proxy-request-1.0 1
  SetEnv proxy-nokeepalive 1
</Location>

</VirtualHost>
```
