### ISSUE TITLE
Making country tag work the same way as language tag

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#37]
When choosing a language tag of a document, said language gets applied / added as a filter; great feature :)

Same feature would be nice to be applied to the country tag too.

**Comment by ccsmart** [comment]
As an addendum, would prefer if consecutively choosing the filters, they would add. Currently they replace.
Removal of a filter would be by deleting it from the filter menu on the right.

**Comment by kohsah** [comment]
Closing this, since the specific problem has been fixed. The comment has been expanded into Issue #51
