### ISSUE TITLE
Locale in URLs 

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#42]
We have URLs like this: 

<https://dev.gawati.org/filter/_lang/en/_count/10/_from/1/_to/10/_q/%7B%22years%22%3A[%222011%22]%7D>

<https://dev.gawati.org/doc/_lang/en/_iri/akn/tg/act/1930-05-16/arrete_no_215/fra@/!main>

The Locale language `/_lang/en` needs to be the first item in the URL 

So the above should become : 
<https://dev.gawati.org/_lang/en/doc/_iri/akn/tg/act/1930-05-16/arrete_no_215/fra@/!main>

**Comment by Arunadevi** [comment]
Updated `i#41-route-name-after-locale` branch.
