### ISSUE TITLE
Feedback from Victor / Kenyalaw, en_US, search filters not displaying

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#46]
Some quick observations I have made;
1.	There is an issue with en_US language (the default url you are redirected to when you type in the gawati server address). Changing the URL from en-US to en or en_KE works fine --- i18next::backendConnector: loading namespace translations for language en-US failed failed parsing /locales/en-US/translations.json to json output @ main.6ad9a518.js:1
2.	The widget/frame to the right of the screen seems not to load any data (is this an issue with my server setup?) -- see below screenshot.
 
![sshot](https://user-images.githubusercontent.com/9324800/37202803-e77e7f22-238b-11e8-96e3-76d3b4cc9df9.png)

**Comment by kohsah** [comment]
@ccsmart I think this can be closed ?

**Comment by kohsah** [comment]
Will close after verfifying Issue #42

**Comment by ccsmart** [comment]
Can be closed, but not related to #42. This one was certificate mismatch.
