### ISSUE TITLE
In Document FullText Search, result pages are not ordered, and excerpts are not shown

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#54]
See page numbers
![image](https://user-images.githubusercontent.com/9324800/37643922-60f524a2-2c22-11e8-9733-a74ed618c4ee.png)

Search excerpts need to be provided with keyword highlights:

> Page 1 <== should be a link
      Some content from the the page surrounding the search result word <more> <== link to PDF page
> Page 5
      Blah blah ... blah <more>

**Comment by kohsah** [comment]
Search results page order has been fixed (https://github.com/gawati/gawati-portal-ui/commit/a1896757bd15911be23cee5aad5de312c2c2dcd5)
