### ISSUE TITLE
Following an in document FT search result link -> address not found

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#55]
example URL bar entry:
https://dev.gawati.org/akn/ng/act/2014-09-08/hb_1302471/eng@/akn_ng_act_2014-09-08_hb_1302471_eng_main.pdf#page=1
might be a configuration issue as well.

**Comment by kohsah** [comment]
@ccsmart  You need to set the GAWATI_DOCUMENT_SERVER to a different domain ... e.g. on lex2 i have set them to be:

>gawati={
GAWATI_PROXY:"https://lex2.akomantoso.com",
GAWATI_DOCUMENT_SERVER:"https://lexdata.akomantoso.com"
}

**Comment by kohsah** [comment]
This issue was fixed
