### ISSUE TITLE
Switch to using React-PDF for loading pdfs on the page

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#6]
Currently standard object tags are used,  we need to compare mobile responsiveness of the current option to react-pdf

**Comment by Arunadevi** [comment]
Fixed on issue-#6 branch

**Comment by kohsah** [comment]
Needs page browsing ui

**Comment by kohsah** [comment]
Two implementations are there in the code-base now ... 

1) DocumentPDF - based on [react-pdf](https://github.com/wojtekmaj/react-pdf). Renders pages, but there is no page browsing UI. needs to be implemented. Loading documents of 100s of pages may not be optimal, we need to have on-demand loading of pages. 

2) DocumentPDF2 - CURRENT DEFAULT - based on [PdfObject](https://pdfobject.com/) which provides a very simple helper API to search to render the appropriate tag as per what is supported by the browser. Does not do any page navigation other than what is provided by the browser. Works well for mobile because it provides the right tags depending on what is supported by the browser.

**Comment by Arunadevi** [comment]
Pagination can be done as shown in
https://github.com/mikecousins/react-pdf-js/blob/master/README.md#usage.
It uses pdf.js which you said will work on iPhones too.  Is there a reason
we reverted back to react-pdf?

**Comment by kohsah** [comment]
Related https://github.com/gawati/gawati-data/issues/7

**Comment by kohsah** [comment]
@Arunadevi Pagination looks like this: 

![image](https://user-images.githubusercontent.com/5685392/35903377-e9bc5ce4-0c04-11e8-97f1-cce839cd2810.png)

Needs to link to individual pages ...

**Comment by Arunadevi** [comment]
Updated pdf-page-links branch. The PDF is scaled to width.  But will not reload upon resizing.  For mobile view, it loads scaled to width.  Should it reload when window is resized?

**Comment by kohsah** [comment]
@Arunadevi lets not do the reload on resizing. its fine as is. Anyway we have to make a try with linearized PDFs or images, so we tackle this problem at that point.
