### ISSUE TITLE
move keycloak.json out of src 

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#65]
Currently keycloak.json is present src/configs.  It gets compiled into the source code when we deploy to production, which makes it difficult to configure. 
For production mode we need to have this in  `static` and load it via an axios get. We can have a selective loading where if it is being loaded in development mode it uses the keycloak.json in `src/configs` and if its in production mode it loads it from `public` (which is the static folder in production mode)

**Comment by kohsah** [comment]
Fixed in 3fd4b5033d8d6cd10191464925b26b0e920bfedc

**Comment by ccsmart** [comment]
configured and picked up by log in
