### ISSUE TITLE
keycloak.json "curl" -> "gawati-portal-ui"

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#70]
breaks demo page

**Comment by ccsmart** [comment]
dont follow... maybe misunderstanding.
in current keycloak.json, resource and clientId  need to be changed from "curl" to "gawati-portal-ui" as current setting "curl" is not a valid gawati.org clientId. So with the shipped "curl" setting, demo page is broken.

**Comment by kohsah** [comment]
@ccsmart ah I see ... ha ha... i thought it was related to the `curl` command :-)

**Comment by kohsah** [comment]
@ccsmart Fixed done.

**Comment by ccsmart** [comment]
verified
