### ISSUE TITLE
Theming items residing in source

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-ui#73]
Some items related to theming are part of source code, should be extracted into or sth equivalent to vars.css or fetched from other site (eg same CMS as other parts of site)

`./src/components/TopBar_00.txt:        <h2>innovative access to law</h2>`
`./src/components/TopBar.js:        <h2>{ T("innovative access to law") }</h2>`

ending up uneditable in
static/js/main.088b65d8.js

**Comment by kohsah** [comment]
@ccsmart  TopBar_00.txt  needs to be deleted
TopBar.js ... that title can be localized, it can be customized in POEditor. so in the en_KE locale they need to just go and change the translation string for "innovative access to law"  i.e its a key value to the actual string

**Comment by ccsmart** [comment]
Should be removed from locale and moved to theme.
A translation should not change a theme / page identity and changiung a theme / pageidentity should nto change a translation.

**Comment by kohsah** [comment]
@ccsmart but ts a literal text just like a label or something that says "Search Results" , you cannot do literal text in CSS, it would mean you cannot internationalize it . For instance  a country has 2 official languages, and the subheading needs to change depending on the language of the site.

**Comment by ccsmart** [comment]
then that would mean that some translateable resources need to be in themes

**Comment by kohsah** [comment]
@ccsmart that is possible, but its really the same thing at the end of the day since you are still editing a localization string (locally or via poeditor)

**Comment by ccsmart** [comment]
difference would be area of responsibility similar as separating UX from core logic and being modular without side effects. Assuming en as a default/fallbck, if i was to install /add a new language, the page personality should not be affected and the new language working without further changes, leaving the default strings for things like the logo title in place.

**Comment by kohsah** [comment]
@ccsmart  OK ... so some strings will move into their own json file in the themes folder.

**Comment by nilamshirke** [comment]
@kohsah for TopBar.js  need to keep title strings to themes custom.json folder and need to move them to default langauge selecetd. need to do this repeatedly based on language selected.

**Comment by kohsah** [comment]
merged into Issue #90 , closing this for now.
