### ISSUE TITLE
Keyword labels don't get loaded on page

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#9]
For a url like this:
```
http://localhost:3000/#/filter/_lang/en/_count/10/_from/1/_to/10/_q/{"keywords"%3A["acteD%E2%80%99huissierDeJustice"]%2C"years"%3A[]}
```

The label does not get loaded in the keyword search box: 

![image](https://user-images.githubusercontent.com/5685392/34553103-b20d6fb4-f14b-11e7-9b1d-81852c02efbc.png)

**Comment by kohsah** [comment]
see b8eb7ef2f1ecea27c6a39c5070dc29529b70dd3f for a fix..which possibly can be improved.

**Comment by kohsah** [comment]
tested fix as working in production system.

**Comment by Arunadevi** [comment]
I don't quite understand why 
`componentWillReceiveProps(nextProps) {
        // we need to always convert the url query to a back-end XQuery
        this.keywordsUILoad(nextProps);
    } `
is required.  The component does not receive updates on the props after it is mounted.

**Comment by kohsah** [comment]
On Tue, Jan 9, 2018 at 7:12 PM, Arunadevi <notifications@github.com> wrote:

> I don't quite understand why
> componentWillReceiveProps(nextProps) { // we need to always convert the
> url query to a back-end XQuery this.keywordsUILoad(nextProps); }
> is required. The component does not receive updates on the props after it
> is mounted.
>

This is required because it ensures the component gets re-rendered when the
URL param changes.

e.g. the changing from --

/filter/_lang/eng/_count/10/_from/1/_to/10/_q/{"keywords"%3A["Beta"]}

to

/filter/_lang/eng/_count/10/_from/1/_to/10/_q/{"keywords"%3A["Alpha]}

will not cause the component to re-rendeer.

having componentWillReceiveProps() passes any prop changes down to the
component (in this case ... the props.match has changed) and lets the the
retrieval function re-render the component if neccessary...

**Comment by kohsah** [comment]
Closing this for now.
