### ISSUE TITLE
GDPR Compliance: Convert web fonts to local fonts

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-ui#98]
Portal-ui uses web-fonts in various places, we need to convert these to local fonts. 

Local fonts need to be served from `/public` from the specific theme folder. 

To do : convert all web font requests to local font requrests. Portal-ui uses various google fonts e.g. 

`https://fonts.googleapis.com/css?family=Montserrat` is referred by the css ... this must be changed to a local call by saving the specific google font locally; `https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2` - it needs to be given a more understandable name .. the name of the font itself. 

Both build and dev modes need to be tested.

**Comment by ccsmart** [comment]
This ticket made me look for the licensing terms and led to reading font reviews and recommendations.
To sum up, i'd like us to try Fira (http://mozilla.github.io/Fira/) font based on one of those reviews (professionally) and as it seems somehow better to me (unprofesionnally).
For comparison:
https://fonts.google.com/specimen/Montserrat
https://fonts.google.com/specimen/Fira+Sans
